"""
Train/evaluate bidirectional cross-attention kcat model.

Expected feature files per split
--------------------------------
protein_tokens.npy    : [N, P, protein_dim]
rxnfp_tokens.npy      : [N, 1, rxnfp_dim]
chemberta_tokens.npy  : [N, R, chemberta_dim]
labels.npy            : [N]
meta.parquet          : aligned metadata

If chemberta_tokens.npy is absent, the script falls back to molbert_tokens.npy
so you can still run the model on the old single-token MolBERT/ChemBERTa
features, but the recommended input is chemberta_tokens.npy generated by
`token_preprocess_bicross.py`.
"""

from __future__ import annotations

import gc
import json
import logging
import math
import random
import sys
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

import numpy as np
import pandas as pd
from scipy.stats import pearsonr, spearmanr
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import RobustScaler, StandardScaler

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.nn.utils import clip_grad_norm_
from torch.utils.data import DataLoader, Dataset

PARENT_DIR = Path(__file__).resolve().parent.parent
if str(PARENT_DIR) not in sys.path:
    sys.path.insert(0, str(PARENT_DIR))
# from model.BCAKcat import KcatBiCrossAttention
# from model.BCAKcat_woRXNFP import KcatBiCrossAttention
# from model.BCAKcat_woChemTokens import KcatBiCrossAttention
# from model.BCAKcat_woCrossAttn import KcatBiCrossAttention
# from model.BCAKcat_reactionOnly import KcatBiCrossAttention
# from model.BCAKcat_proteinToReaction_only import KcatBiCrossAttention
# from model.BCAKcat_proteinOnly import KcatBiCrossAttention
# from model.BCAKcat_reactionToProtein_only import KcatBiCrossAttention
# from model.BCAKcat_woProteinLocalConv import KcatBiCrossAttention
# from model.BCAKcat_woSelfAttn import KcatBiCrossAttention
# from model.BCAKcat import KcatBiCrossAttention
# from model.BCAKcat_RXNFPOnly import KcatBiCrossAttention
# from model.BCAKcat_ChemOnly import KcatBiCrossAttention
from model.BCAKcat import KcatBiCrossAttention


#data
DEFAULT_BASE_FEATURE_DIR = "/home/drink/kcat_model/pmak/supplement/attention/v4/token_PSW_Ch_Improve_noCut"

DEFAULT_SAVE_ROOT = "/home/drink/kcat_model/BCAKcat/Ablation_for_catpred/BCAKcat_result/BCAKcat_10seedMeanEnsemble"
# DEFAULT_SAVE_ROOT = "/home/drink/kcat_model/BCAKcat/Ablation_for_catpred/BCAKcat_result/BCAKcat_woRXNFP_5seedMeanEnsemble"
# DEFAULT_SAVE_ROOT = "/home/drink/kcat_model/BCAKcat/Ablation_for_catpred/BCAKcat_result/BCAKcat_woChemTokens_5seedMeanEnsemble"
# DEFAULT_SAVE_ROOT = "/home/drink/kcat_model/BCAKcat/Ablation_for_catpred/BCAKcat_result/BCAKcat_woCrossAttn_5seedMeanEnsemble"
# DEFAULT_SAVE_ROOT = "/home/drink/kcat_model/BCAKcat/Ablation_for_catpred/BCAKcat_result/BCAKcat_reactionOnly_5seedMeanEnsemble"
# DEFAULT_SAVE_ROOT = "/home/drink/kcat_model/BCAKcat/Ablation_for_catpred/BCAKcat_result/BCAKcat_proteinToReaction_only_5seedMeanEnsemble"
# DEFAULT_SAVE_ROOT = "/home/drink/kcat_model/BCAKcat/Ablation_for_catpred/BCAKcat_result/BCAKcat_proteinOnly_5seedMeanEnsemble_noVal"
# DEFAULT_SAVE_ROOT = "/home/drink/kcat_model/BCAKcat/Ablation_for_catpred/BCAKcat_result/BCAKcat_reactionToProtein_only_5seedMeanEnsemble_noVal"
# DEFAULT_SAVE_ROOT = "/home/drink/kcat_model/BCAKcat/Ablation_for_catpred/BCAKcat_result/BCAKcat_woProteinLocalConv_5seedMeanEnsemble_noVal"
# DEFAULT_SAVE_ROOT = "/home/drink/kcat_model/BCAKcat/Ablation_for_catpred/BCAKcat_result/BCAKcat_woSelfAttn_5seedMeanEnsemble_noVal"
# DEFAULT_SAVE_ROOT = "/home/drink/kcat_model/BCAKcat/Ablation_for_catpred/BCAKcat_result/BCAKcat_rankloss0_5seedMeanEnsemble_noVal"
# DEFAULT_SAVE_ROOT = "/home/drink/kcat_model/BCAKcat/Ablation_for_catpred/BCAKcat_result/BCAKcat_meanPooling_5seedMeanEnsemble_noVal"
# DEFAULT_SAVE_ROOT = "/home/drink/kcat_model/BCAKcat/Ablation_for_catpred/BCAKcat_result/BCAKcat_maxPooling_5seedMeanEnsemble_noVal"
# DEFAULT_SAVE_ROOT = "/home/drink/kcat_model/BCAKcat/Ablation_for_catpred/BCAKcat_result/BCAKcat_attnPooling_5seedMeanEnsemble_noVal"
# DEFAULT_SAVE_ROOT = "/home/drink/kcat_model/BCAKcat/Ablation_for_catpred/BCAKcat_result/BCAKcat_fusionConcat_5seedMeanEnsemble_noVal"
# DEFAULT_SAVE_ROOT = "/home/drink/kcat_model/BCAKcat/Ablation_for_catpred/BCAKcat_result/BCAKcat_fusionGateSum_5seedMeanEnsemble_noVal"
# DEFAULT_SAVE_ROOT = "/home/drink/kcat_model/BCAKcat/Ablation_for_catpred/BCAKcat_result/BCAKcat_RXNFPOnly_5seedMeanEnsemble_noVal"
# DEFAULT_SAVE_ROOT = "/home/drink/kcat_model/BCAKcat/Ablation_for_catpred/BCAKcat_result/BCAKcat_ChemOnly_5seedMeanEnsemble_noVal"
# DEFAULT_SAVE_ROOT = "/home/drink/kcat_model/BCAKcat/Ablation_for_catpred/BCAKcat_result/BCAKcat_attnMeanPooling_5seedMeanEnsemble_noVal"



DEFAULT_TASKS = (
    {
        "task_name": "catpred",
        "train_split": "train",
        "val_split": None,
        "eval_splits": ("test", "ODD"),
    },
    {
        "task_name": "cold_enzyme",
        "train_split": "kcat-random_train",
        "val_split": None,
        "eval_splits": ("kcat-random_test",),
    },
)
@dataclass
class CFG:
    base_feature_dir: str = DEFAULT_BASE_FEATURE_DIR
    save_root: str = DEFAULT_SAVE_ROOT

    epochs: int = 100
    batch_size: int = 32
    # lr: float = 2e-4
    lr: float = 5e-5
    min_lr: float = 1e-7
    weight_decay: float = 1e-5
    # weight_decay: float = 2.5e-6
    warmup_epochs: int = 5
    grad_clip: float = 1.0
    loss: str = "smoothl1"  # smoothl1, mse, l1
    #修改smoothl1_beta参数，调整为0.3，增加模型对小误差的敏感度，可能有助于提升性能。没用，保持0.5
    smoothl1_beta: float = 0.5
    #目前最佳为 d_model=256,dropout=0,num_layers=1,weight_decay=1e-5,lr=1e-4
    rank_loss_weight: float = 0.15 # 增加rank loss权重可能有助于提升模型的排序能力，但过高可能导致训练不稳定。当前设置为0.15，建议在0.1-0.3范围内进行调试以找到最佳值。
    #improve
    d_model: int = 256

    num_heads: int = 4
    num_layers: int = 1
    # num_layers: int = 2
    self_layers: int = 1
    dropout: float = 0.05
    ffn_expansion: int = 4
    pooling: str = "attn_max"  # mean, max, max_mean, attn, attn_mean
    # pooling: str = "max_mean"  # mean, max, max_mean, attn, attn_mean

    fusion: str = "interaction"  # interaction, concat, gated_sum, gated_concat
    #fusion: str = "concat"  # interaction, concat, gated_sum, gated_concat
    #fusion: str = "gated_sum"  # interaction, concat, gated_sum, gated_concat

    use_type_embeddings: bool = True

    num_workers: int = 2
    pin_memory: bool = True
    use_amp: bool = True
    seed: int = 42
    ensemble_seeds: Tuple[int, ...] = (37, 38, 39, 40, 41, 42, 43, 44, 45, 46)
    # ensemble_seeds: Tuple[int, ...] = (38, 39, 40, 41, 42)
    # ensemble_seeds: Tuple[int, ...] = (42,)

    device: str = "cuda" if torch.cuda.is_available() else "cpu"
    label_method: str = "standard"  # standard, robust(差), none
    task_filter: str = "all"
    run_name: str = ""

    tasks: Tuple[Dict[str, Any], ...] = field(default_factory=lambda: DEFAULT_TASKS)


# ===================== Utils =====================
def seed_everything(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def resolve_device(device: str) -> str:
    if device == "cuda" and not torch.cuda.is_available():
        print("CUDA was requested but is not available. Falling back to CPU.")
        return "cpu"
    return device


def cfg_to_dict(cfg: CFG) -> Dict[str, Any]:
    d = asdict(cfg)
    d["tasks"] = [dict(x) for x in cfg.tasks]
    return d


def selected_tasks(cfg: CFG) -> List[Dict[str, Any]]:
    if cfg.task_filter == "all":
        return [dict(t) for t in cfg.tasks]
    out = [dict(t) for t in cfg.tasks if t["task_name"] == cfg.task_filter]
    if not out:
        raise ValueError(f"Unknown task: {cfg.task_filter}")
    return out


def setup_logger(save_dir: Path, task_name: str) -> logging.Logger:
    save_dir.mkdir(parents=True, exist_ok=True)
    logger = logging.getLogger(f"bicross_{task_name}_{save_dir.name}")
    logger.setLevel(logging.INFO)
    logger.handlers.clear()
    logger.propagate = False

    formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")
    file_handler = logging.FileHandler(save_dir / f"train_{task_name}.log", encoding="utf-8")
    file_handler.setFormatter(formatter)
    console_handler = logging.StreamHandler()
    console_handler.setFormatter(formatter)

    logger.addHandler(file_handler)
    logger.addHandler(console_handler)
    return logger


def cosine_lr(optimizer: torch.optim.Optimizer, epoch: int, cfg: CFG) -> float:
    if epoch < cfg.warmup_epochs:
        lr = cfg.lr * (epoch + 1) / max(1, cfg.warmup_epochs)
    else:
        progress = (epoch - cfg.warmup_epochs) / max(1, (cfg.epochs - cfg.warmup_epochs))
        lr = cfg.min_lr + (cfg.lr - cfg.min_lr) * 0.5 * (1 + math.cos(math.pi * progress))
    for param_group in optimizer.param_groups:
        param_group["lr"] = lr
    return lr


def safe_corr(fn, y_true: np.ndarray, y_pred: np.ndarray) -> float:
    if len(y_true) <= 1:
        return 0.0
    if np.std(y_true) == 0 or np.std(y_pred) == 0:
        return 0.0
    try:
        val = float(fn(y_true, y_pred)[0])
    except Exception:
        return 0.0
    return val if np.isfinite(val) else 0.0


def calc_metrics(y_true: Iterable[float], y_pred: Iterable[float]) -> Dict[str, float]:
    y_true = np.asarray(y_true, dtype=np.float64).reshape(-1)
    y_pred = np.asarray(y_pred, dtype=np.float64).reshape(-1)
    mask = np.isfinite(y_true) & np.isfinite(y_pred)
    y_true = y_true[mask]
    y_pred = y_pred[mask]

    if len(y_true) == 0:
        return {"r2": -float("inf"), "pcc": 0.0, "spearman": 0.0, "rmse": float("inf"), "mae": float("inf")}

    if len(y_true) > 1 and np.std(y_true) > 0:
        r2 = float(r2_score(y_true, y_pred))
        if not np.isfinite(r2):
            r2 = -float("inf")
    else:
        r2 = 0.0

    rmse = float(np.sqrt(mean_squared_error(y_true, y_pred)))
    mae = float(mean_absolute_error(y_true, y_pred))
    return {
        "r2": r2,
        "pcc": safe_corr(pearsonr, y_true, y_pred),
        "spearman": safe_corr(spearmanr, y_true, y_pred),
        "rmse": rmse,
        "mae": mae,
    }


def safe_np_load(path: Path):
    try:
        return np.load(path, mmap_mode="r")
    except ValueError as e:
        print(f"[warn] mmap load failed for {path}: {e}")
        print(f"[warn] fallback to normal np.load for {path}")
        return np.load(path)


# ===================== Label scaling =====================
class LabelProcessor:
    def __init__(self, method: str = "standard"):
        self.method = method
        self.scaler = None

    def fit(self, labels: np.ndarray) -> None:
        labels = np.asarray(labels, dtype=np.float32).reshape(-1, 1)
        if self.method == "standard":
            self.scaler = StandardScaler().fit(labels)
        elif self.method == "robust":
            self.scaler = RobustScaler().fit(labels)
        elif self.method == "none":
            self.scaler = None
        else:
            raise ValueError(f"Unsupported label method: {self.method}")

    def transform(self, labels: np.ndarray) -> np.ndarray:
        labels = np.asarray(labels, dtype=np.float32).reshape(-1, 1)
        if self.scaler is None:
            return labels.flatten().astype(np.float32)
        return self.scaler.transform(labels).flatten().astype(np.float32)

    def inverse_transform(self, labels: np.ndarray) -> np.ndarray:
        labels = np.asarray(labels, dtype=np.float32).reshape(-1, 1)
        if self.scaler is None:
            return labels.flatten().astype(np.float32)
        return self.scaler.inverse_transform(labels).flatten().astype(np.float32)

    def state_dict(self) -> Dict[str, Any]:
        state: Dict[str, Any] = {"method": self.method}
        if self.scaler is None:
            state["scaler"] = None
        elif self.method == "standard":
            state["scaler"] = {
                "mean": self.scaler.mean_.tolist(),
                "scale": self.scaler.scale_.tolist(),
                "var": self.scaler.var_.tolist(),
                "n_samples_seen": int(getattr(self.scaler, "n_samples_seen_", 0)),
            }
        elif self.method == "robust":
            state["scaler"] = {
                "center": self.scaler.center_.tolist(),
                "scale": self.scaler.scale_.tolist(),
            }
        else:
            state["scaler"] = None
        return state

    def load_state_dict(self, state_dict: Dict[str, Any]) -> None:
        self.method = state_dict.get("method", self.method)
        scaler_state = state_dict.get("scaler")

        if scaler_state is None:
            self.scaler = None
        elif self.method == "standard":
            self.scaler = StandardScaler()
            self.scaler.mean_ = np.asarray(scaler_state["mean"], dtype=np.float64)
            self.scaler.scale_ = np.asarray(scaler_state["scale"], dtype=np.float64)
            self.scaler.var_ = np.asarray(scaler_state.get("var", np.ones_like(self.scaler.scale_)), dtype=np.float64)
            self.scaler.n_samples_seen_ = int(scaler_state.get("n_samples_seen", 0))
            self.scaler.n_features_in_ = int(len(self.scaler.mean_))
        elif self.method == "robust":
            self.scaler = RobustScaler()
            self.scaler.center_ = np.asarray(scaler_state["center"], dtype=np.float64)
            self.scaler.scale_ = np.asarray(scaler_state["scale"], dtype=np.float64)
            self.scaler.n_features_in_ = int(len(self.scaler.center_))
        else:
            self.scaler = None


# ===================== Dataset =====================
class TokenDataset(Dataset):
    def __init__(self, split_dir: str | Path, label_processor: Optional[LabelProcessor] = None, fit_label_processor: bool = False):
        self.split_dir = Path(split_dir)
        self.protein = safe_np_load(self.split_dir / "protein_tokens.npy")
        self.rxnfp = safe_np_load(self.split_dir / "rxnfp_tokens.npy")

        chemberta_path = self.split_dir / "chemberta_tokens.npy"
        fallback_path = self.split_dir / "molbert_tokens.npy"
        if chemberta_path.exists():
            self.chemberta = safe_np_load(chemberta_path)
            self.chemberta_source = "chemberta_tokens.npy"
        elif fallback_path.exists():
            self.chemberta = safe_np_load(fallback_path)
            self.chemberta_source = "molbert_tokens.npy"
        else:
            raise FileNotFoundError(f"Missing chemberta_tokens.npy or molbert_tokens.npy in {self.split_dir}")

        self.labels = safe_np_load(self.split_dir / "labels.npy")
        self.meta = pd.read_parquet(self.split_dir / "meta.parquet")

        lengths = [len(self.protein), len(self.rxnfp), len(self.chemberta), len(self.labels), len(self.meta)]
        if len(set(lengths)) != 1:
            raise ValueError(f"Length mismatch in {self.split_dir}: {lengths}")

        self.label_processor = label_processor or LabelProcessor()
        if fit_label_processor:
            self.label_processor.fit(self.labels)
        self.labels_proc = self.label_processor.transform(self.labels)

    def __len__(self) -> int:
        return len(self.labels)

    def __getitem__(self, idx: int):
        protein = torch.from_numpy(np.asarray(self.protein[idx]).copy()).float()
        rxnfp = torch.from_numpy(np.asarray(self.rxnfp[idx]).copy()).float()
        chemberta = torch.from_numpy(np.asarray(self.chemberta[idx]).copy()).float()
        label = torch.tensor(float(self.labels_proc[idx]), dtype=torch.float32)
        return protein, rxnfp, chemberta, label

    @property
    def feature_shapes(self) -> Dict[str, List[int]]:
        return {
            "protein": list(self.protein.shape),
            "rxnfp": list(self.rxnfp.shape),
            "chemberta": list(self.chemberta.shape),
            "labels": list(self.labels.shape),
            "chemberta_source": self.chemberta_source,
        }


# ===================== Overlap checks =====================
def exact_overlap_report(train_meta: pd.DataFrame, eval_meta: pd.DataFrame) -> Dict[str, Dict[str, Any]]:
    checks = {
        "sequence": ["sequence"],
        "reaction": ["reaction_smiles"],
        "sequence_reaction_pair": ["sequence", "reaction_smiles"],
    }
    report: Dict[str, Dict[str, Any]] = {}
    for name, cols in checks.items():
        missing = [c for c in cols if c not in train_meta.columns or c not in eval_meta.columns]
        if missing:
            report[name] = {"columns": cols, "skipped": True, "missing_columns": missing}
            continue
        train_set = set(map(tuple, train_meta[cols].astype(str).itertuples(index=False, name=None)))
        eval_set = set(map(tuple, eval_meta[cols].astype(str).itertuples(index=False, name=None)))
        overlap = train_set & eval_set
        report[name] = {
            "columns": cols,
            "train_unique": len(train_set),
            "eval_unique": len(eval_set),
            "overlap_count": len(overlap),
            "overlap_ratio_eval_unique": float(len(overlap) / max(1, len(eval_set))),
        }
    return report

# ===================== Rank Loss =====================
class RankLoss(nn.Module):
    """Pairwise ranking loss."""
    def __init__(self, margin: float = 1.0):
        super().__init__()
        self.margin = margin
 
    def forward(self, pred: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
        # pred: [batch_size]
        # target: [batch_size]
        batch_size = pred.size(0)
        if batch_size < 2:
            return torch.tensor(0.0, device=pred.device)
 
        # Compute pairwise differences
        # pred_diff[i,j] = pred[i] - pred[j]
        pred_diff = pred.unsqueeze(1) - pred.unsqueeze(0)  # [batch, batch]
        target_diff = target.unsqueeze(1) - target.unsqueeze(0)  # [batch, batch]
 
        # Mask where target[i] > target[j]
        mask = (target_diff > 0).float()
        # If target[i] > target[j], we want pred[i] > pred[j]
        # Loss when pred[i] <= pred[j] when target[i] > target[j]
        loss = mask * torch.clamp(self.margin - pred_diff, min=0.0)
 
        # Sum over upper triangle (i > j) to avoid double counting
        upper_mask = torch.triu(torch.ones_like(mask), diagonal=1)
        loss = (loss * upper_mask).sum() / (upper_mask.sum() + 1e-6)
        return loss
# ===================== Train / eval =====================
def make_criterion(cfg: CFG) -> nn.Module:
    if cfg.loss == "smoothl1":
        return nn.SmoothL1Loss(beta=cfg.smoothl1_beta)
    if cfg.loss == "mse":
        return nn.MSELoss()
    if cfg.loss == "l1":
        return nn.L1Loss()
    raise ValueError("loss must be smoothl1, mse, or l1")


def build_model(train_ds: TokenDataset, cfg: CFG) -> Tuple[KcatBiCrossAttention, Dict[str, Any]]:#
    protein_dim = int(train_ds.protein.shape[-1])#shape
    rxnfp_dim = int(train_ds.rxnfp.shape[-1])
    chemberta_dim = int(train_ds.chemberta.shape[-1])
    protein_tokens = int(train_ds.protein.shape[1]) if len(train_ds.protein.shape) == 3 else 1
    rxnfp_tokens = int(train_ds.rxnfp.shape[1]) if len(train_ds.rxnfp.shape) == 3 else 1
    chemberta_tokens = int(train_ds.chemberta.shape[1]) if len(train_ds.chemberta.shape) == 3 else 1

    model_config: Dict[str, Any] = {
        "protein_dim": protein_dim,
        "rxnfp_dim": rxnfp_dim,
        "chemberta_dim": chemberta_dim,
        "d_model": cfg.d_model,
        "num_heads": cfg.num_heads,
        "num_layers": cfg.num_layers,
        "self_layers": cfg.self_layers,
        "dropout": cfg.dropout,
        "ffn_expansion": cfg.ffn_expansion,
        "protein_max_tokens": protein_tokens,
        "reaction_max_tokens": rxnfp_tokens + chemberta_tokens,
        "pooling": cfg.pooling,
        "fusion": cfg.fusion,
        "use_type_embeddings": cfg.use_type_embeddings,
    }
    model = KcatBiCrossAttention(**model_config).to(cfg.device)
    return model, model_config


def run_epoch(
    model: nn.Module,
    loader: DataLoader,
    criterion: nn.Module,
    optimizer: Optional[torch.optim.Optimizer],
    scaler: Optional[torch.cuda.amp.GradScaler],
    device: str,
    cfg: CFG,
    train: bool,
) -> Tuple[float, np.ndarray, np.ndarray]:
    model.train(train)
    total_loss = 0.0
    all_preds: List[np.ndarray] = []
    all_labels: List[np.ndarray] = []
    autocast_enabled = bool(cfg.use_amp and device == "cuda" and torch.cuda.is_available())
    rank_loss_fn = RankLoss() if train else None

    for protein, rxnfp, chemberta, label in loader:
        protein = protein.to(device, non_blocking=True)
        rxnfp = rxnfp.to(device, non_blocking=True)
        chemberta = chemberta.to(device, non_blocking=True)
        label = label.to(device, non_blocking=True).view(-1)

        if train:
            assert optimizer is not None
            optimizer.zero_grad(set_to_none=True)

        with torch.set_grad_enabled(train):
            with torch.cuda.amp.autocast(enabled=autocast_enabled):
                pred = model(protein, rxnfp, chemberta)
                if train:
                    smoothl1_loss = criterion(pred, label)
                    rank_loss = rank_loss_fn(pred, label)
                    # loss = smoothl1_loss + 0.15 * rank_loss
                    loss = smoothl1_loss + cfg.rank_loss_weight * rank_loss

                else:
                    loss = F.smooth_l1_loss(pred, label, beta=cfg.smoothl1_beta)

            if train:
                if scaler is not None and autocast_enabled:
                    scaler.scale(loss).backward()
                    scaler.unscale_(optimizer)
                    clip_grad_norm_(model.parameters(), cfg.grad_clip)
                    scaler.step(optimizer)
                    scaler.update()
                else:
                    loss.backward()
                    clip_grad_norm_(model.parameters(), cfg.grad_clip)
                    optimizer.step()

        total_loss += float(loss.item())
        all_preds.append(pred.detach().cpu().numpy())
        all_labels.append(label.detach().cpu().numpy())

    labels = np.concatenate(all_labels) if all_labels else np.asarray([], dtype=np.float32)
    preds = np.concatenate(all_preds) if all_preds else np.asarray([], dtype=np.float32)
    avg_loss = total_loss / max(1, len(loader))
    return avg_loss, labels, preds


def make_loader(ds: TokenDataset, cfg: CFG, shuffle: bool) -> DataLoader:
    return DataLoader(
        ds,
        batch_size=cfg.batch_size,
        shuffle=shuffle,
        num_workers=cfg.num_workers,
        pin_memory=bool(cfg.pin_memory and cfg.device == "cuda"),
        drop_last=False,
    )


def predict_processed(model: nn.Module, loader: DataLoader, device: str, cfg: CFG) -> np.ndarray:
    model.eval()
    preds: List[np.ndarray] = []
    autocast_enabled = bool(cfg.use_amp and device == "cuda" and torch.cuda.is_available())
    with torch.no_grad():
        for protein, rxnfp, chemberta, _ in loader:
            protein = protein.to(device, non_blocking=True)
            rxnfp = rxnfp.to(device, non_blocking=True)
            chemberta = chemberta.to(device, non_blocking=True)
            with torch.cuda.amp.autocast(enabled=autocast_enabled):
                pred = model(protein, rxnfp, chemberta)
            preds.append(pred.detach().cpu().numpy())
    return np.concatenate(preds) if preds else np.asarray([], dtype=np.float32)


def evaluate_split(
    model: nn.Module,
    split_dir: Path,
    split_name: str,
    train_ds: TokenDataset,
    criterion: nn.Module,
    cfg: CFG,
    save_dir: Path,
    logger: logging.Logger,
) -> Dict[str, float]:
    ds = TokenDataset(split_dir, label_processor=train_ds.label_processor, fit_label_processor=False)
    loader = make_loader(ds, cfg, shuffle=False)
    loss, labels_proc, preds_proc = run_epoch(model, loader, criterion, optimizer=None, scaler=None, device=cfg.device, cfg=cfg, train=False)

    labels_raw = ds.label_processor.inverse_transform(labels_proc)
    preds_raw = ds.label_processor.inverse_transform(preds_proc)
    metrics = calc_metrics(labels_raw, preds_raw)
    metrics["loss"] = float(loss)

    pred_df = ds.meta.copy()
    pred_df["y_true"] = labels_raw
    pred_df["y_pred"] = preds_raw
    pred_df["error"] = pred_df["y_pred"] - pred_df["y_true"]
    pred_df["abs_error"] = pred_df["error"].abs()
    pred_df.to_csv(save_dir / f"predictions_{split_name}.csv", index=False)

    with open(save_dir / f"metrics_{split_name}.json", "w", encoding="utf-8") as f:
        json.dump(metrics, f, ensure_ascii=False, indent=2)

    logger.info(
        "Eval %s | loss=%.4f | r2=%.4f | pcc=%.4f | spearman=%.4f | rmse=%.4f | mae=%.4f",
        split_name,
        metrics["loss"],
        metrics["r2"],
        metrics["pcc"],
        metrics["spearman"],
        metrics["rmse"],
        metrics["mae"],
    )
    return metrics


def task_save_dir(cfg: CFG, task_name: str) -> Path:
    suffix = f"_{cfg.run_name}" if cfg.run_name else ""
    return Path(cfg.save_root) / f"{task_name}{suffix}"


def train_one_seed(
    cfg: CFG,
    task_name: str,
    train_split: str,
    val_split: Optional[str],
    eval_splits: Tuple[str, ...],
    seed: int,
) -> Dict[str, Any]:
    seed_everything(seed)
    task_dir = Path(cfg.base_feature_dir) / task_name
    train_dir = task_dir / train_split
    save_dir = task_save_dir(cfg, task_name) / f"seed_{seed}"
    logger = setup_logger(save_dir, task_name)

    logger.info("Task: %s", task_name)
    logger.info("Seed: %d", seed)
    logger.info("Train dir: %s", train_dir)
    logger.info("Val dir: None (no validation; final checkpoint only)")
    
    # 记录关键配置参数
    logger.info("=" * 80)
    logger.info("Training Parameters:")
    logger.info("  epochs: %d", cfg.epochs)
    logger.info("  batch_size: %d", cfg.batch_size)
    logger.info("  lr: %.6f", cfg.lr)
    logger.info("  min_lr: %.6f", cfg.min_lr)
    logger.info("  weight_decay: %.6f", cfg.weight_decay)
    logger.info("  warmup_epochs: %d", cfg.warmup_epochs)
    logger.info("  grad_clip: %.2f", cfg.grad_clip)
    logger.info("  loss: %s", cfg.loss)
    logger.info("  label_method: %s", cfg.label_method)
    logger.info("  device: %s", cfg.device)
    logger.info("  seed: %d", seed)
    logger.info("=" * 80)
    logger.info("Model Parameters:")
    logger.info("  d_model: %d", cfg.d_model)
    logger.info("  num_heads: %d", cfg.num_heads)
    logger.info("  num_layers: %d", cfg.num_layers)
    logger.info("  self_layers: %d", cfg.self_layers)
    logger.info("  dropout: %.2f", cfg.dropout)
    logger.info("  ffn_expansion: %d", cfg.ffn_expansion)
    logger.info("  pooling: %s", cfg.pooling)
    logger.info("  fusion: %s", cfg.fusion)
    logger.info("  use_type_embeddings: %s", cfg.use_type_embeddings)
    logger.info("=" * 80)
    logger.info("Data Parameters:")
    logger.info("  num_workers: %d", cfg.num_workers)
    logger.info("  pin_memory: %s", cfg.pin_memory)
    logger.info("  use_amp: %s", cfg.use_amp)
    logger.info("=" * 80)

    label_processor = LabelProcessor(cfg.label_method)
    train_ds = TokenDataset(train_dir, label_processor=label_processor, fit_label_processor=True)

    logger.info("Train samples: %d", len(train_ds))
    logger.info("Train feature shapes: %s", json.dumps(train_ds.feature_shapes, ensure_ascii=False))

    train_loader = make_loader(train_ds, cfg, shuffle=True)

    model, model_config = build_model(train_ds, cfg)
    optimizer = torch.optim.AdamW(model.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay)
    criterion = make_criterion(cfg)
    scaler = torch.cuda.amp.GradScaler(enabled=(cfg.use_amp and cfg.device == "cuda" and torch.cuda.is_available()))

    history: List[Dict[str, Any]] = []
    start_time = time.time()

    for epoch in range(cfg.epochs):
        current_lr = cosine_lr(optimizer, epoch, cfg)
        train_loss, train_labels_proc, train_preds_proc = run_epoch(
            model, train_loader, criterion, optimizer, scaler, cfg.device, cfg, train=True
        )

        train_labels_raw = train_ds.label_processor.inverse_transform(train_labels_proc)
        train_preds_raw = train_ds.label_processor.inverse_transform(train_preds_proc)

        train_metrics = calc_metrics(train_labels_raw, train_preds_raw)

        logger.info(
            "Epoch %03d | lr=%.6g | train_loss=%.4f | "
            "train_r2=%.4f | train_pcc=%.4f | train_spearman=%.4f | train_rmse=%.4f | train_mae=%.4f",
            epoch + 1,
            current_lr,
            train_loss,
            train_metrics["r2"],
            train_metrics["pcc"],
            train_metrics["spearman"],
            train_metrics["rmse"],
            train_metrics["mae"],
        )

        row = {
            "epoch": epoch + 1,
            "lr": current_lr,
            "train_loss": train_loss,
            **{f"train_{k}": v for k, v in train_metrics.items()},
        }
        history.append(row)

    total_time = time.time() - start_time
    logger.info(
        "Finished training %s seed=%d. Final epoch=%d, hours=%.2f",
        task_name,
        seed,
        cfg.epochs,
        total_time / 3600,
    )

    pd.DataFrame(history).to_csv(save_dir / "history.csv", index=False)

    final_ckpt = {
        "epoch": cfg.epochs,
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "label_processor": train_ds.label_processor.state_dict(),
        "history": history,
        "cfg": cfg_to_dict(cfg),
        "model_config": model_config,
        "feature_shapes": train_ds.feature_shapes,
        "seed": seed,
        "checkpoint_type": "final",
    }
    torch.save(final_ckpt, save_dir / "final_model.pth")
    logger.info("Saved final checkpoint: %s", save_dir / "final_model.pth")

    eval_model = model
    eval_model.eval()
    eval_results: Dict[str, Dict[str, float]] = {}
    for split in eval_splits:
        split_dir = task_dir / split
        if not split_dir.exists():
            logger.warning("Eval split does not exist, skip: %s", split_dir)
            continue

        eval_ds_for_overlap = TokenDataset(split_dir, label_processor=train_ds.label_processor, fit_label_processor=False)
        overlap_report = exact_overlap_report(train_ds.meta, eval_ds_for_overlap.meta)
        with open(save_dir / f"overlap_train_vs_{split}.json", "w", encoding="utf-8") as f:
            json.dump(overlap_report, f, ensure_ascii=False, indent=2)
        logger.info("Exact overlap train vs %s: %s", split, json.dumps(overlap_report, ensure_ascii=False))
        del eval_ds_for_overlap

        eval_results[split] = evaluate_split(eval_model, split_dir, split, train_ds, criterion, cfg, save_dir, logger)

    summary = {
        "task_name": task_name,
        "seed": seed,
        "final_epoch": cfg.epochs,
        "train_split": train_split,
        "val_split": val_split,
        "eval_results": eval_results,
        "note": "No validation, no early stopping, no best-model selection. Per-seed metrics use the final checkpoint.",
        "hours": total_time / 3600,
        "cfg": cfg_to_dict(cfg),
        "model_config": model_config,
        "feature_shapes": train_ds.feature_shapes,
    }
    with open(save_dir / "summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    feature_shapes = train_ds.feature_shapes
    del model, optimizer, train_loader, train_ds
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return {
        "seed": int(seed),
        "final_epoch": int(cfg.epochs),
        "hours": total_time / 3600,
        "seed_dir": str(save_dir),
        "eval_results": eval_results,
        "model_config": model_config,
        "feature_shapes": feature_shapes,
    }


def summarize_seed_metrics(per_seed_metrics: List[Dict[str, float]]) -> Dict[str, Dict[str, float]]:
    keys = ("r2", "pcc", "spearman", "rmse", "mae", "loss")
    summary: Dict[str, Dict[str, float]] = {}
    for key in keys:
        values = np.asarray([m[key] for m in per_seed_metrics if key in m and np.isfinite(m[key])], dtype=np.float64)
        if len(values) == 0:
            continue
        summary[key] = {
            "mean": float(np.mean(values)),
            "std": float(np.std(values, ddof=0)),
            "min": float(np.min(values)),
            "max": float(np.max(values)),
        }
    return summary


def mean_ensemble_models(
    cfg: CFG,
    task_name: str,
    train_split: str,
    eval_splits: Tuple[str, ...],
    seed_results: List[Dict[str, Any]],
) -> Dict[str, Dict[str, Any]]:
    task_dir = Path(cfg.base_feature_dir) / task_name
    save_dir = task_save_dir(cfg, task_name)
    logger = setup_logger(save_dir, task_name)

    logger.info("=" * 80)
    logger.info("10-seed mean ensemble evaluation for task: %s", task_name)
    logger.info("Seeds: %s", tuple(r["seed"] for r in seed_results))
    logger.info("=" * 80)

    models: List[nn.Module] = []
    label_processors: List[LabelProcessor] = []
    for result in seed_results:
        ckpt_path = Path(result["seed_dir"]) / "final_model.pth"
        if not ckpt_path.exists():
            raise FileNotFoundError(f"Missing final checkpoint for seed {result['seed']}: {ckpt_path}")
        ckpt = load_checkpoint(ckpt_path, map_location=cfg.device)

        label_processor = LabelProcessor()
        label_processor.load_state_dict(ckpt["label_processor"])
        label_processors.append(label_processor)

        model = KcatBiCrossAttention(**ckpt["model_config"]).to(cfg.device)
        model.load_state_dict(ckpt["model_state_dict"])
        model.eval()
        models.append(model)

    train_ds_for_overlap = TokenDataset(task_dir / train_split, label_processor=label_processors[0], fit_label_processor=False)
    ensemble_results: Dict[str, Dict[str, Any]] = {}

    for split in eval_splits:
        split_dir = task_dir / split
        if not split_dir.exists():
            logger.warning("Eval split does not exist, skip: %s", split_dir)
            continue

        ds = TokenDataset(split_dir, label_processor=label_processors[0], fit_label_processor=False)
        loader = make_loader(ds, cfg, shuffle=False)
        labels_raw = np.asarray(ds.labels, dtype=np.float32).reshape(-1)
        raw_preds_all: List[np.ndarray] = []
        per_seed_metrics: List[Dict[str, float]] = []

        overlap_report = exact_overlap_report(train_ds_for_overlap.meta, ds.meta)
        with open(save_dir / f"ensemble_overlap_train_vs_{split}.json", "w", encoding="utf-8") as f:
            json.dump(overlap_report, f, ensure_ascii=False, indent=2)
        logger.info("Exact overlap train vs %s: %s", split, json.dumps(overlap_report, ensure_ascii=False))

        for result, model, label_processor in zip(seed_results, models, label_processors):
            preds_proc = predict_processed(model, loader, cfg.device, cfg)
            preds_raw = label_processor.inverse_transform(preds_proc)
            raw_preds_all.append(preds_raw)
            metrics = calc_metrics(labels_raw, preds_raw)
            per_seed_metrics.append(metrics)
            logger.info(
                "Split %s | seed=%d | r2=%.4f | pcc=%.4f | spearman=%.4f | rmse=%.4f | mae=%.4f",
                split,
                result["seed"],
                metrics["r2"],
                metrics["pcc"],
                metrics["spearman"],
                metrics["rmse"],
                metrics["mae"],
            )

        stacked_preds = np.stack(raw_preds_all, axis=0)
        ensemble_pred = np.mean(stacked_preds, axis=0)
        ensemble_metrics = calc_metrics(labels_raw, ensemble_pred)
        per_seed_summary = summarize_seed_metrics(per_seed_metrics)

        logger.info(
            "Mean ensemble %s | r2=%.4f | pcc=%.4f | spearman=%.4f | rmse=%.4f | mae=%.4f",
            split,
            ensemble_metrics["r2"],
            ensemble_metrics["pcc"],
            ensemble_metrics["spearman"],
            ensemble_metrics["rmse"],
            ensemble_metrics["mae"],
        )

        pred_df = ds.meta.copy()
        pred_df["y_true"] = labels_raw
        pred_df["y_pred"] = ensemble_pred
        pred_df["error"] = pred_df["y_pred"] - pred_df["y_true"]
        pred_df["abs_error"] = pred_df["error"].abs()
        for i, result in enumerate(seed_results):
            pred_df[f"pred_seed_{result['seed']}"] = stacked_preds[i]
        pred_df.to_csv(save_dir / f"ensemble_predictions_{split}.csv", index=False)

        per_seed_df = pd.DataFrame(
            [{"seed": seed_results[i]["seed"], **per_seed_metrics[i]} for i in range(len(seed_results))]
        )
        per_seed_df.to_csv(save_dir / f"per_seed_metrics_{split}.csv", index=False)

        result_payload = {
            "method": "mean_prediction_ensemble",
            "seeds": [int(r["seed"]) for r in seed_results],
            "metrics": ensemble_metrics,
            "per_seed_metrics": per_seed_df.to_dict(orient="records"),
            "per_seed_metric_summary": per_seed_summary,
        }
        with open(save_dir / f"ensemble_metrics_{split}.json", "w", encoding="utf-8") as f:
            json.dump(result_payload, f, ensure_ascii=False, indent=2)

        ensemble_results[split] = result_payload
        del ds, loader

    del models, train_ds_for_overlap
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return ensemble_results


def train_one_task(cfg: CFG, task_name: str, train_split: str, val_split: Optional[str], eval_splits: Tuple[str, ...]) -> None:
    save_dir = task_save_dir(cfg, task_name)
    logger = setup_logger(save_dir, task_name)
    save_dir.mkdir(parents=True, exist_ok=True)
    if len(cfg.ensemble_seeds) != 10:
        logger.warning("Expected 10 ensemble seeds, got %d: %s", len(cfg.ensemble_seeds), cfg.ensemble_seeds)

    logger.info("=" * 80)
    logger.info("10-seed mean prediction ensemble training for task: %s", task_name)
    logger.info("Seeds: %s", cfg.ensemble_seeds)
    logger.info("=" * 80)

    start_time = time.time()
    seed_results: List[Dict[str, Any]] = []
    for seed in cfg.ensemble_seeds:
        logger.info("Start seed %d", seed)
        result = train_one_seed(
            cfg,
            task_name=task_name,
            train_split=train_split,
            val_split=val_split,
            eval_splits=eval_splits,
            seed=seed,
        )
        seed_results.append(result)
        logger.info("Finished seed %d | final_epoch=%d", seed, result["final_epoch"])

    ensemble_results = mean_ensemble_models(cfg, task_name, train_split, eval_splits, seed_results)

    total_time = time.time() - start_time
    pd.DataFrame(seed_results).to_csv(save_dir / "seed_summary.csv", index=False)
    summary = {
        "task_name": task_name,
        "train_split": train_split,
        "val_split": val_split,
        "eval_splits": list(eval_splits),
        "run_mode": "10_seed_mean_prediction_ensemble_no_val_final_checkpoint",
        "ensemble_method": "mean_prediction",
        "ensemble_seeds": [int(seed) for seed in cfg.ensemble_seeds],
        "seed_results": seed_results,
        "ensemble_results": ensemble_results,
        "hours": total_time / 3600,
        "cfg": cfg_to_dict(cfg),
    }
    with open(save_dir / "summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    logger.info("=" * 80)
    logger.info("Finished 10-seed mean ensemble for task: %s | hours=%.2f", task_name, total_time / 3600)
    logger.info("=" * 80)


def load_checkpoint(path: Path, map_location: str):
    try:
        return torch.load(path, map_location=map_location, weights_only=False)
    except TypeError:
        return torch.load(path, map_location=map_location)

def main() -> None:
    cfg = CFG()
    seed_everything(cfg.seed)
    Path(cfg.save_root).mkdir(parents=True, exist_ok=True)

    for task in selected_tasks(cfg):
        print("=" * 80)
        print(f"Training task: {task['task_name']}")
        train_one_task(
            cfg,
            task_name=task["task_name"],
            train_split=task["train_split"],
            val_split=task["val_split"],
            eval_splits=tuple(task["eval_splits"]),
        )


if __name__ == "__main__":
    main()
